# -*- coding: utf-8 -*-
"""Data Processing for Mahjong Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XqJntYK0thtqPpZdDr13ZbmuIGkxu27A
"""

import os
import json

KAGGLE_USERNAME = "#"
KAGGLE_KEY = "#"

os.makedirs('/root/.kaggle', exist_ok=True)
with open('/root/.kaggle/kaggle.json', 'w') as f:
    json.dump({'username': KAGGLE_USERNAME, 'key': KAGGLE_KEY}, f)
!chmod 600 /root/.kaggle/kaggle.json
print('Kaggle Credentials Done')

!pip install kaggle -q
!kaggle datasets download -d hphphp123321/tenhou-4-player-riichi-mahjong-dataset -p /content/mahjong/ --unzip -q
print('Download Done')
!ls /content/mahjong/