# -*- coding: utf-8 -*-
"""Mahjong CNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rR5r_A3BZabRXvBmDWfUCs7BhCgvPvZa
"""

import torch
import torch.nn as nn

#34 by 15, 510
#input size/layer is 34 * 15, output is who won game (revisit this)
#nodes can be implemented later
#connects with each other..

class MahjongCnn(nn.Module):
  def __init__(self):
      super().__init__()

    #input layer, 34*15
      self.convLayerOne = nn.Conv2d(in_channels = 1, out_channels = 100, kernel_size = (5, 3))
      self.relu1 = nn.ReLU()
      self.maxPool1 = nn.MaxPool2d(kernel_size = (5, 3))


    #fully connected layers lowk idk wat that means im sorry
      self.fc = nn.Linear(2400, 34)

  #moves stuff forward, data goes through da layers
  def forward(self, x):
    #basically push it through each layer and then return output
      output = self.convLayerOne(x)
      output = self.relu1(output)
      output = self.maxPool1(output)
      output = out.reshape(out.size(0), -1)
      output = self.fc(output)

    return output